---
title:  "Spatial Protein Imaging Webinar:Cell Clustering and Annotation"
author: "Mahla Asghari"
date:   "2026-05-20"
---

Link to data:

https://indiana-my.sharepoint.com/:f:/g/personal/masghari_iu_edu/IgA5WSuYAR5YQZYd7Gf17vDOAfmImJjewkr07Uv98iZb-5I?e=oxoqB4


# ###########################################
# ----------- Load Libraries ----------------

```{r}
library(data.table)
library(FastPG)
library(umap)
library(ggplot2)
library(gtools)
library(dplyr)
library(tidyr)
library(reshape2)
```
# ###########################################
# ----- Load and integrate samples ---------

```{r}
### Make Sample list
sample.list <- list.files(path = "./samples/", full.names = FALSE, recursive = FALSE)    #point to the directory with the csvs

tissue.list <- substr(sample.list, 5,11)    #second number could even be higher just to grab the ".csv"
region.list <- substr(sample.list, 5,11)

### Load samples
import <- fread(paste("./samples/", sample.list[[1]], sep = ""))

channel_labels_atlas <- c("MPO","CD8","CD3","CD45RO","CD20","CD4","Ki67","CD45","CD11c","GATA3","Vimentin","FOXP3",
                          "SLC12A3","OPN","PLSCR1",'Nestin',"VCAM1","KIM1","AQP1","CD90","pMLKL",'CD123','CD56','WT_1',
                          "pcJUN","MCP1","Cystatin3", "LC3",
                          "Fibronectin","PROM1","CD31","NaKATPase","IGFBP7","Ecadherin","Podocalyxin","CollagenIV", "Bcatenin",
                          "LRP2","CD68","aSMA","AQP2","CD206","HLA-DR","UMOD","Cytokeratin8")   

### Generate data frames
import.list <- list()
import.scaled.list <- list()

data <- data.frame()
data.scaled <- data.frame()
data.normalized <- data.frame()
data.combined <- data.frame()
import.scaled <- data.frame()
import.normalized <- data.frame()
import.raw <- data.frame()
features.names <- c("Object", "X", "Y", "Z", channel_labels_atlas)   #gives columns names   

for (i in 1:length(x = sample.list )) {
  import <- fread(paste("./samples/", sample.list[[i]], sep = "")) #point to the directory with the csvs   
  print(paste(sample.list[[i]], dim(import)))
  import.list[[i]] <- import
  ### !!!TBD below - needs to be adjusted based on the exported csv!!!
  import <- import[,c(1,2,3,4,334, 341, 348, 355, 362, 369, 12, 383, 390, 15,
                      404, 17, 418, 425, 432, 439, 446, 453, 460, 467,
                      26, 481, 488, 495, 30, 509, 516, 523, 530, 537,
                      544, 551, 558, 565, 572, 579, 586, 593, 600, 607,
                      614, 621, 628, 635, 642)]    
  
  colnames(import) <- features.names
  import$Biopsy <- substr(sample.list[[i]], 5,11)#5 and 11 refers to the number of the first characters it's taking (substrings)
  import$CSV = sample.list[[i]]
  
  print(paste(sample.list[[i]], dim(import)))    #gives number of rows and cols
 
  import.scaled <- data.frame(import)
  import.scaled <- scale(import.scaled[,c(-1, -2, -3, -4, -50, -51,-52)], center= TRUE, scale=TRUE)     #adjust !!!
  
  import.normalized <- data.frame(import)
  import.normalized <- import.normalized[,c(-1, -2, -3, -4, -50, -51,-52)] + 1      #adjust !!!
  import.normalized <- log10(import.normalized)
  
  data <- smartbind(data,  data.frame(import))
  data.scaled <- smartbind(data.scaled, import.scaled)
  data.normalized <- smartbind(data.normalized, import.normalized)
  data.combined.build <-cbind(data.frame(import), data.frame(import))
  data.combined <- smartbind(data.combined, data.combined.build)
  import.raw <- smartbind(data.frame(import), import.raw) 
}

data.normalized.scaled <- data.frame(scale(data.normalized, center= TRUE, scale=TRUE))


#convert zero to NA
data [is.na(data)] <- 0
data.scaled [is.na(data.scaled)] <- 0
data.normalized [is.na(data.normalized)] <- 0
data.combined [is.na(data.combined)] <- 0
data.normalized.scaled [is.na(data.normalized.scaled)] <- 0
import.raw[is.na(import.raw)] <- 0


data.normalized.scaled$Biopsy <- data.combined$Biopsy
data.normalized.scaled$Object <- data.combined$Object
#data.normalized.scaled$Region <- region #'Cortex' or 'Medulla'_these 2 samples are cortex

data.normalized$Biopsy <- data.combined$Biopsy
data.normalized$Object <- data.combined$Object
#data.normalized$Region <- region # 'Cortex' or 'Medulla'_these 2 samples are cortex

data.scaled$Biopsy <- data.combined$Biopsy
data.scaled$Object <- data.combined$Object
#data.scaled$Region <- region # 'Cortex' or 'Medulla'_these 2 samples are cortex

import.raw$Biopsy <- data.combined$Biopsy
import.raw$Object <- data.combined$Object

# add coordinates to scaled data
data.scaled$X=data.combined$X
data.scaled$Y=data.combined$Y


# Save
saveRDS(import.raw, "./rawData")
saveRDS(data.normalized, "./datanormalized")
saveRDS(data.normalized.scaled, "./datanormalizedscaled")
saveRDS(data.combined, "./datacombined")
saveRDS(data.scaled, "./datascaled")

```
# ###########################################
# ----------- Clustering and UMAP -----------

```{r}
# Load data
CM.data.scaled <- readRDS('./datascaled')
colnames(CM.data.scaled)
# Define clustering features(markers)
cols=c("WT_1","Podocalyxin","Nestin","LRP2","AQP1","CD90","SLC12A3","UMOD",
  "AQP2","Ecadherin","NaKATPase","PROM1","VCAM1","CD31","Fibronectin",
  "Vimentin","aSMA","CD45","Cytokeratin8","Bcatenin")

data.embedding <- CM.data.scaled[, cols]
set.seed(42) 
clusters_200_CM <- FastPG::fastCluster(as.matrix(data.embedding), 200, 8) #Adjust K value according to the dataset size!!

#Add clusters to scaled data
CM.data.scaled$cluster <- clusters_200_CM$communities

#remove rows with NA
CM.data.scaled <- CM.data.scaled[,colSums(is.na(CM.data.scaled))==0] 

#save file
saveRDS(CM.data.scaled, "./ScaledClusters")

### run UMAP
umap <- umap(data.embedding)# Use clustering features for the UMAP

#Adding umap coordiantes to dataset
CM.data.scaled$umap1=umap$layout[, 1]
CM.data.scaled$umap2=umap$layout[, 2]

saveRDS(umap,'./umap')
saveRDS(CM.data.scaled,'./scaled_umap_clusters')



```
# ###########################################
# ------------- Visualization ---------------

```{r}

# Define color palette

newCol=c( "#DE3163","#9D6BB3","#CDE645","#F57C00","#008000","#8AB9F1","#B31B1B","#E6A817","#FFEB3B",
          "#FFB7C5","#79B336","#CCCCFF","#F1DDCF","#A8516E","#264980","#AF6E4D","#CCEBC5","#7B1FA2",
          "#7FFFD4","#674846","#682860","#0000FF","#FF5800","#D32F2F", "#00BFFF","#20B2AA","#B9D9EB",
          "#504D80","#FF61C3","#6CB4EE", "#85B09A","#DF73FF","#C04000","#F88379","#ffadad","#C0C0C0",
          "#66C2A5","#ecf39e")

# Load data
data2=readRDS('./scaled_umap_clusters')

# Define and subset markers for plots(Optional)
cols_2=c("WT_1","Podocalyxin","Nestin","LRP2","AQP1","CD90","SLC12A3","AQP2","UMOD",
       "Cytokeratin8","Ecadherin","NaKATPase","Bcatenin","PROM1",
       "VCAM1","CD31","Fibronectin","Vimentin","aSMA","CD45","Biopsy",
       "cluster","umap1","umap2")
data=data2[,cols_2]

##------------------------- UMAPs ----------------------------------

### UMAP of Clusters
ggplot(data, aes(x = umap1, y = umap2, colour = as.factor(cluster))) + 
  geom_point(size = 1, stroke = 0.1, alpha = 0.7) +
  theme_classic() + 
  scale_color_manual(values =newCol ) +
  guides(colour = guide_legend(override.aes = list(shape = 15, size = 5))) + 
  theme(legend.title = element_blank(), legend.key.size = unit(1.0, "cm"), 
        legend.text = element_text(size = 12)
  ) 
                               
                                   
### UMAP of Samples
ggplot(data, aes(x = umap1, y = umap2, colour = as.factor(Biopsy))) + 
  geom_point(size = 1, stroke = 0.1, alpha = 0.7) +
  theme_classic() + 
  scale_color_manual(values =c('#2B4593','#B9D9EB') ) +
  guides(colour = guide_legend(override.aes = list(shape = 15, size = 5))) + 
  theme(legend.title = element_blank(), legend.key.size = unit(1.0, "cm"), 
        legend.text = element_text(size = 12)
  ) 

##-------------------- Violin Plot -------------------------
cols=c("WT_1","Podocalyxin","Nestin","LRP2","AQP1","CD90","SLC12A3","UMOD",
       "AQP2","Ecadherin","NaKATPase","PROM1","VCAM1","CD31","Fibronectin",
       "Vimentin","aSMA","CD45","Cytokeratin8","Bcatenin")

markers=colnames(data)[1:20]
data.melt <- data[, c(1:20, 22)] %>%
  pivot_longer(
    cols = all_of(markers),
    names_to = "Marker",
    values_to = "Intensity"
  )

data.melt$Marker <- factor(data.melt$Marker,levels=cols)
ggplot(data.melt, aes(x = factor(cluster), y = Intensity, fill = as.factor(cluster))) +
  geom_violin(scale = "width", adjust = 1.5, trim = TRUE) +
  facet_wrap(~ Marker, scales = "free_y", ncol = 5) +  
  theme_classic() +
  scale_fill_manual(values = newCol) +  
  theme(axis.text.x = element_text(size = 15, hjust = 0.5,color = 'black'),
        strip.text = element_text(size = 15),  
        legend.position = "none") +
  labs(x = "Cluster", y = "Intensity" )

##----------------------- Heatmap -------------------------
markers <- colnames(data)[1:20]
colnames(data)

# Subset clustering column and selected marker features for plotting
hm_mat=data[,c(1:20,22)]
colnames(hm_mat)

heatmap <- hm_mat %>%
  select(all_of(markers), cluster) %>% group_by(cluster) %>% 
  summarise(across(all_of(markers), ~median(., na.rm = TRUE))) %>%
  as.data.frame()

#convert to long format
df_long <- heatmap %>%pivot_longer(cols = -cluster,
    names_to = "Marker",values_to = "Value")

# Set factor levels to control the ordering of markers and clusters in the plot
df_long$Marker <- factor(df_long$Marker, levels = rev(cols))
cluster_levels=c(11,13,1,0,9,8,10,4,2,3,5,12,6,7)
df_long$cluster <- factor(df_long$cluster, levels =cluster_levels)

range(df_long$Value)

# plot Heatmap
ggplot(df_long, aes(x = cluster, y = Marker, fill = Value)) +
  geom_tile(color = "grey80", size = 0.4) +scale_fill_gradient2(
    low ="#B9D9EB" , mid = "white", high ="#AB274F",
    midpoint = 0, limits = c(-1,3),oob = scales::squish # Adjust the limits according to data range
  ) + theme_minimal(base_size = 11) +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, size = 12,
                                   vjust = 0.5,color = 'black',face='bold'),
    axis.text.y = element_text(size = 12,face='bold',color = 'black'),
    panel.grid = element_blank(),axis.title = element_blank(),
    legend.title = element_text(size = 10),legend.key.height = unit(0.4, "cm"))


```
# ###########################################
# --------- Immune subclustering ------------

```{r}
# Define immune features for clustering
immune.markers=c("CD45","MPO","CD8","CD4","CD3","CD45RO","CD20",
                 "FOXP3","CD11c","CD123","CD56","CD206","CD68")
immune <- data2[data2$cluster%in% c(7),]#choose immune cluster

data.immune <- immune[,immune.markers ]
colnames(data.immune)
set.seed(42) 
clusters_immune <- FastPG::fastCluster(as.matrix(data.immune), 100, 8) #Adjust K  
immune$cluster_imm <- clusters_immune$communities#Add clusters to scaled data
immune <- immune[,colSums(is.na(immune))==0] #remove rows with NA
#saveRDS(immune, "./immune_ScaledClusters")

#Run UMAP on Immune subclusters
umap_immune <- umap(data.immune)#keep clustering features for UMAP

#Adding umap to data.subset.umap
immune$umap1_immune=umap_immune$layout[, 1]
immune$umap2_immune=umap_immune$layout[, 2]

#saveRDS(umap_immune,'./umap_immune')
#saveRDS(immune,'./scaled_Immune_umap_clusters')
```
# ###########################################################
# --------- Immune subclusters plots ----------------------

```{r}
immune <- readRDS('scaled_Immune_umap_clusters')
newCol_2=c( "#DE3163","#9D6BB3","#CDE645","#F57C00","#008000","#264980",
            "#B31B1B","#8AB9F1","#FFEB3B", "#FFB7C5","#79B336","#CCCCFF",
            "#F1DDCF","#A8516E","#264980","#AF6E4D","#CCEBC5","#7B1FA2")
# UMAP of Immune cell subclusters
ggplot(immune, aes(x = umap1_immune, y = umap2_immune, colour = as.factor(cluster_imm))) + 
  geom_point(size = 2, stroke = 0.1, alpha = 0.7) +
  theme_classic() + 
  scale_color_manual(values =newCol_2 ) +
  guides(colour = guide_legend(override.aes = list(shape = 15, size = 5))) + 
  theme(legend.title = element_blank(), legend.key.size = unit(1.0, "cm"), 
        legend.text = element_text(size = 12)
  ) 

#UMAP of samples
ggplot(immune, aes(x = umap1_immune, y = umap2_immune, colour = as.factor(Biopsy))) + 
  geom_point(size = 2, stroke = 0.1, alpha = 0.7) +
  theme_classic() + 
  scale_color_manual(values =c('#2B4593','#B9D9EB') ) +
  guides(colour = guide_legend(override.aes = list(shape = 15, size = 5))) + 
  theme(legend.title = element_blank(), legend.key.size = unit(1.0, "cm"), 
        legend.text = element_text(size = 12)
  ) 

##------------- Violin Plot -------------------------

immune.markers=c("CD45","MPO","CD8","CD4","CD3","CD45RO","CD20",
                 "FOXP3","CD11c","CD123","CD56","CD206","CD68")

imm_sub <- immune[, c("cluster_imm", immune.markers)]
#make the long format of table
data.melt.immune <- imm_sub %>%
  pivot_longer(cols = all_of(immune.markers),names_to = "Marker",values_to = "Intensity" )

# Set cluster factor levels in ascending order to ensure consistent ordering in plots
data.melt.immune$cluster_imm <- factor(data.melt.immune$cluster_imm,levels=sort(unique(immune$cluster_imm)))

# Set marker factor levels based on predefined marker list to control display order
data.melt.immune$Marker <- factor(data.melt.immune$Marker,levels=immune.markers)

# Violin plots
ggplot(data.melt.immune, aes(x = factor(cluster_imm), y = Intensity, fill = as.factor(cluster_imm))) + geom_violin(scale = "width", adjust = 1.5, trim = TRUE) +
  facet_wrap(~ Marker, scales = "free_y", ncol = 4) +  
  theme_classic() + scale_fill_manual(values = newCol_2) +  
  theme(axis.text.x = element_text(size = 13, hjust = 0.5,color = 'black'),
        strip.text = element_text(size = 15),  
        legend.position = "none") + abs(x = "Cluster", y = "Intensity" )



##-------------------- heatmap -------------------------

immune.markers=c("CD45","MPO","CD8","CD4","CD3","CD45RO","CD20",
                 "FOXP3","CD11c","CD123","CD56","CD206","CD68")

imm_sub <- immune[, c("cluster_imm", immune.markers)]
# get median of celltypes in each cluster
heatmap_imm <- imm_sub %>%
  select(all_of(immune.markers), cluster_imm) %>%  
  group_by(cluster_imm) %>% 
  summarise(across(all_of(immune.markers), ~median(., na.rm = TRUE))) %>%
  as.data.frame()

#convert to long format
df_long_imm <- heatmap_imm %>%pivot_longer(
    cols = -cluster_imm,names_to = "Marker",
    values_to = "Value" )

df_long_imm$Marker <- factor(df_long_imm$Marker, levels = immune.markers)
df_long_imm$cluster_imm <- factor(df_long_imm$cluster_imm, levels = c(0:11))
#saveRDS(df_long_imm,'./heatmap_Input_immune')
range(df_long_imm$Value)
# Heatmap
ggplot(df_long_imm, aes(x = cluster_imm, y = Marker, fill = Value)) +
  geom_tile(color = "grey80", size = 0.4) +scale_fill_gradient2(
    low ="#B9D9EB" , mid = "white", high ="#AB274F",
    midpoint = 0, limits = c(-1,3),oob = scales::squish # Adjust the limits according to data range
  ) + theme_minimal(base_size = 11) +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, size = 12,vjust = 0.5,color = 'black',face='bold'),
    axis.text.y = element_text(size = 12,face='bold',color = 'black'),
    panel.grid = element_blank(),axis.title = element_blank(),
    legend.title = element_text(size = 10),legend.key.height = unit(0.4, "cm"))




```
# ###########################################################
# -----Merge immune subclusters into the full dataset--------


```{r}
immune <- readRDS('scaled_Immune_umap_clusters')
all=readRDS('./scaled_umap_clusters')

#the final cluster in main data is 13,rename immune subclusters by adding 14 levels 
immune$cluster_2 <- (immune$cluster_imm)+14
table(immune$cluster_2)
table(immune$cluster_imm)

#subset columns
out=immune[,c("Biopsy","Object","cluster_2")]

#merge Immune subcluster to main dataset
all=left_join(all,out,by = c("Biopsy","Object"))
unique(all$cluster_2)# Non immune clusters will get NA  

#replace NA with actual non-immune clusters
all$cluster_2 <- ifelse(is.na(all$cluster_2), all$cluster, all$cluster_2)

table(all$cluster_2)
table(immune$cluster_2)
table(all$cluster)

#------------------------ VLN plot ---------------------------
col_sub=c("WT_1","Podocalyxin","Nestin","LRP2","AQP1","CD90","SLC12A3","AQP2","UMOD",
       "Cytokeratin8","Ecadherin","NaKATPase","Bcatenin","PROM1",
       "VCAM1","CD31","Fibronectin","Vimentin","aSMA","CD45","Biopsy",
       "cluster_2","umap1","umap2")
all_sub=all[,col_sub]# subset dataset 
markers_2=colnames(all_sub)[1:20] # define markers to plot

#convert table to long format
data.melt_1 <- all_sub[, c(1:20, 22)] %>%
  pivot_longer(cols = all_of(markers_2),
    names_to = "Marker",values_to = "Intensity"  )

#define levels of markers in plot
data.melt_1$Marker <- factor(data.melt_1$Marker,levels=col_sub[1:20])

ggplot(data.melt_1, aes(x = factor(cluster_2), y = Intensity, fill = as.factor(cluster_2))) +
  geom_violin(scale = "width", adjust = 1.5, trim = TRUE) +
  facet_wrap(~ Marker, scales = "free_y", ncol = 5) +  
  theme_classic() +
  scale_fill_manual(values = newCol) + #find the color palette in visualization section 
  theme(axis.text.x = element_text(size = 11, hjust = 0.5,color = 'black'),
        strip.text = element_text(size = 11),  
        legend.position = "none") +
  labs(x = "Cluster", y = "Intensity" )

```

# ###########################################################
# --------- Bakmapping data preparation--------------------
# ###########################################################

```{r}

#------Update object----
df=readRDS('scaled_umap_clusters')

sort(unique(df$cluster))
colnames(df)

# Extract columns object, Biopsy, cluster
subset_df <- df[, c( "Biopsy","Object", "cluster")] 

# Rename columns to match VTEA-required format
colnames(subset_df) <- c( "Biopsy","Object", "Cluster") 

# Loop over each Biopsy and subset the data, then save as CSV
biopsies <- unique(subset_df$Biopsy)
output_dir <- "./"  

for (biopsy_value in biopsies) {
    biopsy_subset <- subset(subset_df, Biopsy == biopsy_value)# subset by Biopsy
    biopsy_subset <- biopsy_subset[, !names(biopsy_subset) %in% "Biopsy"]# remove Biopsy column
    file_name <- file.path(output_dir, paste0("sample_", biopsy_value, ".csv")) # build file name
    write.csv(biopsy_subset, file = file_name, row.names = FALSE)# write CSV
}


```





